version: '3.9'
services:
  backend:
    build: 
      context: ./backend
    ports:
      - "4001:4001"
    environment:
      - HOST=db
      - PORT=3306
      - USER=root
      - PASSWORD=password
      - DATABASE=mydb
    env_file: 
      - .env
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend
