version: '3.9'
services:
  backend:
    build: 
      context: ./backend
    ports:
      - "4001:4001"
    environment:
      - HOST=db
      - PORT=3306
      - USER=root
      - PASSWORD=password
      - DATABASE=mydb
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"
